..
.de TQ
.br
.ns
.TP \\$1
..
.TH OpenFT.conf 5 "21 June 2002" "OpenFT version 0.0.4-1" 
.SH NAME
OpenFT.conf \- configuration file for OpenFT, used by
.BR giFT (1)
.SH DESCRIPTION
.B OpenFT.conf
uses a very basic configuration file format. It's divided in sections, starting
with
.RB [ sectionname "]."
parameters are set using 
.RB ` parameter " = " value '.
Lines starting with 
.B #
are comments.
.P
The file must be located at
.IR ~/.giFT/OpenFT/OpenFT.conf .
.SH OPTIONS
.SS [main]
Main options
.TP
.B class
Node classification.  This value is very important and will determine your
role on the network.
.IP
The following settings are allowed:
.IP
.IR 1 " USER"
.br
.IR 3 " SEARCH"
.br
.IR 5 " INDEX"
.br
.IR 7 " SEARCH & INDEX"
.IP
If you unsure it is highly recommended that you select 1.  More information
may be found by consulting other documentation.
.IP
.I "Default: "
1
.TP
.B port 
Core listening port.  OpenFT uses a compacted binary protocol for the core
communication with other nodes.  If this machine is unable to provide both
port and http_port to the outside directly (blocked by either by a firewall
or a NAT setup) you should select 0 here.
.IP
.BI NOTE:
If you are unable to route this port (along with the HTTP port) you will be
unable to download from other users with that same inability.  You have
been warned.
.IP
.I "Default: "
1215
.TP
.B http_port
HTTP server port.  OpenFT's implementation also makes use of HTTP for all
file transfers.  See above for more details.
.IP
.I "Default: "
1216
.SS [search]
Search node settings
.TP
.B children
Maximum number of "child" nodes you are able to support.  You should not
touch this unless you know what you're doing.
.IP
.BI NOTE:
This option has no effect unless you configure as a SEARCH node.
.IP
.I "Default: "
500
.SS [local]
LAN mode facilities
.TP
.B lan_mode
OpenFT offers a special configuration for users who wish to operate a
network from within a local area network (LAN).  This mode causes giFT to
reject authorization from any non-local address as well as advertising it's
presence via the local UDP broadcast.  If this switch is non-zero you will
not be able to contact the main network.
.IP
.I "Default: "
0
.TP 
.B hosts_allow
When lan_mode is set to non-zero this configuration switch is used to
verify which hosts are allowed connection to the core OpenFT port.  It is
highly recommended that you just don't touch this, regardless of what
lan_mode's value is.
.IP
.BI NOTE:
This switch provides a very crude loophole that could allow you to create
a "private" OpenFT network between a list of known nodes.  Using this
"feature" is going to be quite cumbersome as it is intended to be used
by developers only.  You have been warned.
.IP
.I "Default: "
LOCAL
.SH AUTHOR
Josh Guilfoyle <jasta@gotlinux.org>. Made into a manpage by Eelco Lempsink
<eelco@33lc0.net>
.SH "SEE ALSO"
.BR giFT (1), 
.BR gift.conf (5),
http://gift.sourceforge.net/docs/
