# $Id: Makefile.msvc,v 1.13 2002/10/17 09:45:37 rossta Exp $
# Microsoft Visual C++ 6.0 makefile
# see README.msvc for usage

MAKEOPTS=-nologo -C

all:
	cd win32
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
	cd ..\lib
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
!if defined(static) || defined(STATIC)
	cd ..\OpenFT
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
	cd ..\src
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
	@cd ..
!else
	cd ..\src
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
	cd ..\OpenFT
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc
	@cd ..
!endif

install: win32-dist
	cd lib
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
!if defined(static) || defined(STATIC)
	cd ..\OpenFT
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
	cd ..\src
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
!else
	cd ..\src
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
	cd ..\OpenFT
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
!endif
	cd ..\data
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
	cd ..\etc
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc install
	@cd ..


clean:
	cd lib
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc clean
	cd ..\src
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc clean
	cd ..\OpenFT
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc clean
	cd ..\win32
	@$(MAKE) $(MAKEOPTS) -f Makefile.msvc clean
	@cd ..
  
clean-dist:
	@del /f win32-dist

win32-dist:
	@-md win32-dist
	@-md win32-dist\data
	@-md win32-dist\data\OpenFT
	@-md win32-dist\OpenFT
